Adboard/Adboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from .views import index, page_not_found, server_error

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('ann/', include('announcement.urls')),
    path('cab/', include('cabinet.urls')),
    path('com/', include('coment.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = page_not_found
handler500 = server_error

Adboard/announcement/urls.py
from django.urls import path

from announcement.views import BoardListView, BoardPageListView, PageCreateView, PageDestroyView, PageUpdateView

urlpatterns = [
    path('v1/adboard/', BoardListView.as_view(), name="board_list"),
    path('v1/adboard/page/create/', PageCreateView.as_view(), name="board-page-create"),
    path('v1/adboard/page/<int:id>/', BoardPageListView.as_view(), name="board_page"),
    path('v1/adboard/page/<int:id>/destroy/', PageDestroyView.as_view(), name="board_page-destroy"),
    path('v1/adboard/page/<int:id>/update/', PageUpdateView.as_view(), name="board_page-update"),
]

Adboard/coment/urls.py
from django.urls import path
from .views import CommentCreateView, UserCommentList, PostCommentList, CommentAcceptedUpdateView

urlpatterns = [
    path('v1/add-comment/<int:id>/', CommentCreateView.as_view(), name='add-comment'),
    path('v1/<str:username>/my-comment/', UserCommentList.as_view(), name='my-comment'),
    path('v1/<str:username>/<int:id>/comments-to-post/', PostCommentList.as_view(), name='comments-to-post'),
    path('v1/comments-to-accepted/<int:id>/', CommentAcceptedUpdateView.as_view(), name='to-accepted'),
]

Adboard/announcement/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils.translation import gettext_lazy as _
from datetime import datetime

from cabinet.models import User


def post_media_directory_path(instance, filename) -> str:
    """
     Приложение announcement, Модель Post. Формирование пути для атрибута upload_to=
    """
    date = datetime.now()
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return f"announcement/{instance.author}/{date.year}/{date.month}/{date.day}/{filename}"


class Post(models.Model):
    """
    Публикации. Публикация имеет одного автора и одну категорию. К публикациям возможны комментарии.
    """
    author = models.ForeignKey(
        to=User,
        to_field='username',
        related_name='posts',
        on_delete=models.CASCADE,
        verbose_name='Автор'
    )
    category = models.ForeignKey(
        to='Category',
        to_field='categories',
        related_name='posts',
        on_delete=models.CASCADE,
        verbose_name='Категории'
    )
    title = models.CharField(max_length=100, unique=True, verbose_name='Заголовок')
    article = models.TextField(max_length=5000, verbose_name='Содержание')
    images = models.ImageField(upload_to=post_media_directory_path, blank=True, null=True, verbose_name="Картинки")
    files = models.FileField(upload_to=post_media_directory_path, blank=True, null=True, verbose_name="Файлы медиа")
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'
        ordering = ['id']

    def preview(self):
        article = self.article[:150]
        return article + ' ...'

    @property
    def images_url(self):
        if self.images and hasattr(self.images, 'url'):
            return self.images.url

    @property
    def files_url(self):
        if self.files and hasattr(self.files, 'url'):
            return self.files.url

    def __str__(self):
        return f"{self.author}: {self.category} - {self.title[:20]}"

    def get_comment_my_post_url(self):
        """ view in coment """
        return reverse(viewname='comments-to-post', kwargs={'username': self.author.username, 'id': self.id})

    def get_absolute_url(self):
        return reverse(viewname='board_page', kwargs={'id': self.id})


class Category(models.Model):
    """
    Категории публикаций
    """

    class Categories(models.TextChoices):
        # A .label property is added on values, to return the human-readable name.
        TANK = 'TK', _('Танки')
        HEALTH = 'HL', _('Хилы')
        DD = 'DD', _('ДД')
        MERCHANT = 'MCH', _('Торговцы')
        GUILDMASTER = 'GM', _('Гилдмастеры')
        QUESTGIVER = 'QG', _('Квестгиверы')
        FARRIER = 'FR', _('Кузнецы')
        TANNER = 'TN', _('Кожевники')
        POTIONMAKER = 'PM', _('Зельевары')
        SPELLMASTERS = 'SM', _('Мастера заклинаний')

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['id']

    categories = models.CharField(max_length=18, choices=Categories.choices, default=Categories.TANK, unique=True,
                                  verbose_name='Категории')

    def __str__(self):
        return f"{self.categories}"

Adboard/announcement/forms.py
from django import forms

from .models import Post, Category


class FormPost(forms.ModelForm):
    """ Форма для создания и изменения публикации """

    category = forms.ChoiceField(choices=Category.Categories.choices, label="Категории")

    class Meta:
        model = Post
        fields = ["category", "title", "article", "images", "files"]
        widgets = {
            "category": forms.Select(attrs={'class': 'form-select'}),  # от чего-то не влияет ...
            "title": forms.TextInput(attrs={'class': 'form-input'}),
            "article": forms.Textarea(attrs={'class': 'form-textarea', 'rows': 15})
        }

Adboard/announcement/views.py
import re

from django.shortcuts import redirect
from rest_framework.exceptions import APIException, ValidationError
from rest_framework.generics import get_object_or_404
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework.renderers import TemplateHTMLRenderer, JSONRenderer
from rest_framework.response import Response
from rest_framework import generics, permissions, status
from django_filters.rest_framework import DjangoFilterBackend

from cabinet.models import User
from .filters import BoardListFilter
from .forms import FormPost
from .models import Post
from .pagination import BoardListPagination
from .serializer import BoardSerializer, BoardPageSerializer
from .services import correct_form_category_for_serializer


class BoardListView(generics.ListAPIView):
    """ Вывод карточек всех объявлений на странице """

    serializer_class = BoardSerializer
    permission_classes = [permissions.AllowAny]
    queryset = Post.objects.filter().all().order_by('-date_create')
    pagination_class = BoardListPagination
    filter_backends = [DjangoFilterBackend]
    filterset_class = BoardListFilter
    renderer_classes = [JSONRenderer, TemplateHTMLRenderer]
    template_name = "announcement/board_title.html"

    def get(self, request, *args, **kwargs):
        # все танцы с фильтрацией из-за пагинации в основном для TemplateHTMLRenderer, а так могло бы работать штатно.
        queryset = self.get_queryset()
        filter_board = self.filterset_class(self.request.GET, queryset)
        qs = filter_board.qs
        self.pagination_class.len_filter_qs = len(qs)  # для подсчета числа страничек, по другому будет глючить
        pages = self.paginate_queryset(queryset=qs)

        if request.headers.get('Content-Type') == 'application/json':
            if pages is not None:
                serializer = self.get_serializer(pages, many=True)
                return self.get_paginated_response(serializer.data)
            return self.list(request, *args, **kwargs)

        if pages is not None:
            return self.get_paginated_response(pages)
        return Response({"board_list": qs, "pagination": False})


class BoardPageListView(generics.ListAPIView):
    """ Вывод страницы с объявлением """

    serializer_class = BoardSerializer
    permission_classes = [permissions.AllowAny]
    renderer_classes = [JSONRenderer, TemplateHTMLRenderer]
    template_name = "announcement/board_page.html"

    def get_queryset(self):
        queryset = Post.objects.filter(pk=self.kwargs['id'])
        return queryset

    def get(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        if not list(queryset):
            data = {'error': 'Такой страницы нет либо записей нет.', 'status': 'HTTP_404_NOT_FOUND'}
            if request.headers.get('Content-Type') == 'application/json':
                return Response(data, status=status.HTTP_404_NOT_FOUND)
            return Response({'error': data}, template_name='announcement/page_error.html')

        if request.headers.get('Content-Type') == 'application/json':
            return self.list(request, *args, **kwargs)
        return Response({'board_page': queryset})


class PageCreateView(generics.ListCreateAPIView):
    """ Создание нового объявления """

    serializer_class = BoardPageSerializer
    permission_classes = [permissions.IsAuthenticated]
    parser_classes = (MultiPartParser, FormParser)  # без этого с формы ничего не получить
    renderer_classes = [JSONRenderer, TemplateHTMLRenderer]
    template_name = "announcement/create_page.html"

    def get(self, request, *args, **kwargs):
        # метод get из-за TemplateHTMLRenderer
        if request.headers.get('Content-Type') == 'application/json':
            return Response(data={"Detail": "Метод GET не разрешен"}, status=status.HTTP_200_OK)

        user = User.objects.filter(username=request.user.username)
        form = FormPost()
        return Response({"profile": user, "form": form})  # "serializer": self.get_serializer() трудно настроить стили

    def post(self, request, *args, **kwargs):
        data = correct_form_category_for_serializer(request=request)
        serializer = BoardPageSerializer(data=data, context={'request': request})
        header = re.compile(r"^multipart/form-data")

        if not serializer.is_valid():
            data_err = {'error': serializer.errors, 'status': 'HTTP_400_BAD_REQUEST'}
            if header.search(request.headers.get('Content-Type')) and data.get('mark') is None:
                return Response(data_err, status=status.HTTP_400_BAD_REQUEST)
            return Response(data={'error': data_err}, template_name='announcement/page_error.html')

        if serializer.is_valid(raise_exception=True):
            try:
                serializer.save()
            except ValidationError as e:  # лимит на публикации
                data_err = {'error': e.detail, 'status': 'HTTP_400_BAD_REQUEST'}
                if header.search(request.headers.get('Content-Type')) and data.get('mark') is None:
                    return Response(data_err, status=status.HTTP_400_BAD_REQUEST)
                return Response({'error': data_err}, template_name='announcement/page_error.html')
            except APIException:
                data_err = {'error': 'Сервер не отвечает.', 'status': 'HTTP_500_INTERNAL_SERVER_ERROR'}
                if header.search(request.headers.get('Content-Type')) and data.get('mark') is None:
                    return Response(data_err, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
                return Response({'error': data_err}, template_name='announcement/page_error.html')

            if header.search(request.headers.get('Content-Type')) and data.get('mark') is None:
                return Response(serializer.data, status=status.HTTP_201_CREATED)
            return redirect('board_list')


class PageUpdateView(generics.RetrieveUpdateAPIView):
    """ Контроллер изменения объявления """

    serializer_class = BoardPageSerializer
    permission_classes = [permissions.IsAuthenticated]
    parser_classes = (MultiPartParser, FormParser)
    renderer_classes = [JSONRenderer, TemplateHTMLRenderer]
    template_name = "announcement/update_page_form.html"

    def get_queryset(self):
        queryset = Post.objects.filter(id=self.kwargs['id'])
        return queryset

    def get_object(self):
        obj = Post.objects.get(id=self.kwargs['id'])
        return obj

    def get(self, request, *args, **kwargs):
        if Post.objects.filter(id=self.kwargs['id']).exists():
            if Post.objects.get(id=self.kwargs['id']).author == request.user:
                if request.headers.get('Content-Type') == 'application/json':
                    return self.retrieve(request, *args, **kwargs)

                user = User.objects.filter(username=request.user.username)
                queryset = self.get_queryset()
                initial = {
                    "category": queryset[0].category,
                    "title": queryset[0].title,
                    "article": queryset[0].article,
                }
                form = FormPost(initial=initial)  # instance=queryset[0] все поля или initial переопределить поля
                return Response({"profile": user, "posts": queryset, "form": form})

        if request.headers.get('Content-Type') == 'application/json':
            return Response(data={"error": "Тут ничего нет!"}, status=status.HTTP_204_NO_CONTENT)
        return redirect("board_list")

    def post(self, request, *args, **kwargs):
        data = correct_form_category_for_serializer(request=request)
        instance = get_object_or_404(Post, id=kwargs['id'])  # можно еще так self.get_object()
        serializer = BoardPageSerializer(instance=instance, data=data, context={'request': request})
        header = re.compile(r"^multipart/form-data")

        if instance.author != request.user:
            if header.search(request.headers.get('Content-Type')) and data.get('mark') is None:
                return Response(data={"error": "Тут ничего нет!"}, status=status.HTTP_204_NO_CONTENT)
            return redirect("board_list")

        if not serializer.is_valid():
            data_err = {'error': serializer.errors, 'status': 'HTTP_400_BAD_REQUEST'}
            if header.search(request.headers.get('Content-Type')) and data.get('mark') is None:
                return Response(data_err, status=status.HTTP_400_BAD_REQUEST)
            return Response({'error': data_err}, template_name='announcement/page_error.html')

        if serializer.is_valid():
            try:
                # Если в .save() добавить owner=other/dict/, то добавит в validated_data и можно будет пользовать
                serializer.save()
            except APIException:
                data_err = {'error': 'Сервер не отвечает.', 'status': 'HTTP_500_INTERNAL_SERVER_ERROR'}
                if header.search(request.headers.get('Content-Type')) and data.get('mark') is None:
                    return Response(data_err, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
                return Response({'error': data_err}, template_name='announcement/page_error.html')

            if header.search(request.headers.get('Content-Type')) and data.get('mark') is None:
                data_ = {'state': 1, 'message': 'Изменение прошло успешно'}
                return Response(data_, status=status.HTTP_200_OK)
            return redirect('board_list')


class PageDestroyView(generics.DestroyAPIView):
    """ Удаление объявления """

    serializer_class = BoardPageSerializer
    permission_classes = [permissions.IsAuthenticated]
    renderer_classes = [JSONRenderer, TemplateHTMLRenderer]
    template_name = "announcement/destroy_page.html"
    queryset = Post.objects.all()

    def get_object(self):
        obj = get_object_or_404(self.queryset, id=self.kwargs['id'])
        return obj

    def destroy(self, request, *args, **kwargs):

Adboard/templates/announcement/board_page.html
{% extends 'announcement/flatpages/default.html' %}
{% load cabinet_tags %}

{% block title %}
Автор
{% endblock title %}

{% block header %}
    <h2>Объявление/публикация</h2>
{% endblock header %}

{% block nav-content %}
<div class="nav-content">
    <ul>
        <li><a href="{% url 'board_list' %}">К публикациям</a></li>
        {% if request.user.is_authenticated %}
        <li><a href="{% url 'add-comment' board_page.0.id %}">Оставить комментарий</a></li>
        {% endif %}
    </ul>
</div>
<div class="nav-content">
    <hr>
    <h3>Автор</h3>
    <p>{{board_page.0.author.username}}</p>
    {% if board_page.0.author.photo %}
    <div class="block-author-img">
        <img src="{{board_page.0.author.photo.url}}" alt="Автор"/>
    </div>
    {% endif %}
</div>
{% endblock nav-content %}

{% block article-content %}
<div class="page-container">
{% for p in board_page %}
    <div class="page-item-1">
        <span>Автор: {{p.author.username}}</span>
    </div>
    <div class="page-item-2">
        <span>Категория: {{p.category.get_categories_display}}</span>
    </div>
    <div class="page-item-3">
        <span>Дата публикации: {{p.date_create}}</span>
    </div>
    <div class="page-item-4">
        <h3>{{p.title}}</h3>
    </div>
    {% if p.images %}
    <div class="page-item-5">
        <img src="{{p.images.url}}" alt="Картинка"/>
    </div>
    {% endif %}
    <div class="page-item-6">
        <p>{{p.article|linebreaks}}</p>
    </div>
    {% if p.files %}
    <div class="page-item-7">
        <embed src="{{p.files.url}}" type="image/gif">
    </div>
    {% endif %}
{% endfor %}
</div>
<div class="comment-block">
    <h3>Комментарии:</h3>
{% for p in board_page %}
    <div class="page-item-8">
    {% for com in p.comment.all %}
        <div class="com-content">
            <div class="com-ava">
                <div class="com-img">
                    {% if com.author.photo %}
                        <img src="{{com.author.photo.url}}" alt="Автор"/>
                    {% else %}
                        <img src="{% get_media_prefix %}default\Orc.jpg" alt="Аватарка"/>
                    {% endif%}
                </div>
            </div>
            <div class="com-name">
                <span> {{com.author.username}}:</span>
            </div>
            <div class="com-comment">
                <span> {{com.comment}}</span>
            </div>
        </div>
    {% endfor %}
    </div>
{% endfor %}
</div>
{% endblock article-content %}

Adboard/templates/announcement/board_title.html
{% extends 'announcement/flatpages/default.html' %}

{% block header %}
    <h2>Доска объявлений</h2>
{% endblock header %}


{% block nav-content %}
{% if request.user.is_authenticated %}
<div class="nav-content">
    <ul>
        <li><a href="{% url 'profile' user.id %}">Моя страница</a></li>
        <li><a href="{% url 'board-page-create' %}">Добавить объявление</a></li>
    </ul>
</div>
{% endif %}
<div class="nav-content">
    <hr>
    <h3>Фильтрация</h3>
    {% include 'announcement/filters.html' %}
</div>
{% if pagination %}
<div class="nav-content">
    <hr>
    <h3>Пагинация</h3>
    <div class="pagination">
        <span>Всего записей: {{count}}</span><br>
    </div>
    {% include 'announcement/paginator/numbers.html' %}
</div>
{% endif %}
{% endblock nav-content %}

{% block article-content %}
{% for post in board_list %}
<div class="post-title">
    <div class="post-top_side">
        <div class="title-title">
            <h3>{{post.title|truncatechars:30}}</h3>
        </div>
        {% if post.images %}
            <div class="post-image">
                <img src="{{post.images.url}}" alt="Image"/>
            </div>
        {% endif %}
        <div class="post-previews">
            <p>{{post.preview}}</p>
        </div>
    </div>
    <div class="post-underside">
        <div class="line">
            <div class="line-1">
                <p>Кат.: {{post.category.get_categories_display}}</p>
            </div>
            <div class="line-1">
                <p>Автор: {{post.author.username}}</p>
            </div>
        </div>
        <div class="line">
            <div class="line-1">
                <p>{{post.date_create}}</p>
            </div>
            <div class="post-link line-1">
                <a href="{{post.get_absolute_url}}">Смотреть</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock article-content %}

Adboard/templates/announcement/create_page.html
{% extends 'cabinet/profile.html' %}

{% block content-list %}
<div class="content-container">
    <h2 align="center">Создание объявления</h2>

    <div class="body-title">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-block">
                <div class="block-1"><label for="{{ form.category.id_for_label }}"> {{form.category.label}}: </label></div>
                <div class="block-2">
                    {{form.category}}
                    <span>{{form.category.errors}}</span>
                </div>
            </div>
            <div class="form-block">
                <div class="block-1"><label for="{{ form.title.id_for_label }}">{{form.title.label}}:</label></div>
                <div class="block-2">
                    {{form.title}}
                    <span> {{form.title.errors}} </span>
                </div>
            </div>
            <div class="form-block">
                <div class="block-1"><label for="{{ form.article.id_for_label }}">{{form.article.label}}:</label></div>
                <div class="block-2">
                    {{form.article}}
                    <span> {{form.article.errors}} </span>
                </div>
            </div>
            <div class="form-block">
                <div class="block-1"><label for="{{ form.images.id_for_label }}">{{form.images.label}}:</label></div>
                <div class="block-2">
                    {{form.images}}
                    <span> {{form.images.errors}} </span>
                </div>
            </div>
            <div class="form-block">
                <div class="block-1"><label for="{{ form.files.id_for_label }}">{{form.files.label}}:</label></div>
                <div class="block-2">
                    {{form.files}}
                    <span> {{form.files.errors}} </span>
                </div>
            </div>
            <input hidden="hidden" name="mark" value="True">
            <br>
            <input type="submit" value="Сохранить">
        </form>
        <br>
        <div>
            <a href="{% url 'board_list' %}"> К публикациям </a>
        </div>
    </div>
</div>
{% endblock content-list %}

Adboard/templates/announcement/destroy_page.html
{% extends 'cabinet/flatpages/default.html' %}

{% block article-content %}
<div class="content-container">
    <div class="body-title" style="width:60%">
        <h3>Удалить публикацию?</h3>
        <div class="form-block">
            <div class="block-1">
                <form method="POST">
                    {% csrf_token %}
                    <button type="submit">Удалить</button>
                </form>
            </div>
            <div class="block-1">
                <form action="{% url 'profile' profile.0.id %}" method="GET">
                    <input type="submit" value="Нет">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock article-content %}

Adboard/templates/announcement/filters.html
<div class="filters">
<form class="filter-form" method="GET">
    {% csrf_token %}
    <label class="label-form-r" for="author">Автор:</label><input class="input-form-r" type="text" id="author" name="author" maxlength="100" placeholder="например: serg"><br>
    <label class="label-form-r" for="date_after">Дата от:</label><input class="input-form-r" type="date" id="date_after" name="date_after"><br>
    <label class="label-form-r" for="date_before">Дата до:</label><input class="input-form-r" type="date" id="date_before" name="date_before"><br>
    <label class="label-form-r">Категория:</label> <div class="input-form-r"></div>
    <input class="input-form" type="checkbox" name="category" id="tank" value="TK"><label class="label-form" for="tank">Танки</label><br>
    <input class="input-form" type="checkbox" name="category" id="health" value="HL"><label class="label-form" for="health">Хилы</label><br>
    <input class="input-form" type="checkbox" name="category" id="dd" value="DD"><label class="label-form" for="dd">ДД</label><br>
    <input class="input-form" type="checkbox" name="category" id="merchant" value="MCH"><label class="label-form" for="merchant">Торговцы</label><br>
    <input class="input-form" type="checkbox" name="category" id="guildmaster" value="GM"><label class="label-form" for="guildmaster">Гилдмастеры</label><br>
    <input class="input-form" type="checkbox" name="category" id="questgiver" value="QG"><label class="label-form" for="questgiver">Квестгиверы</label><br>
    <input class="input-form" type="checkbox" name="category" id="farrier" value="FR"><label class="label-form" for="farrier">Кузнецы</label><br>
    <input class="input-form" type="checkbox" name="category" id="tanner" value="TN"><label class="label-form" for="tanner">Кожевники</label><br>
    <input class="input-form" type="checkbox" name="category" id="potionmarker" value="PM"><label class="label-form" for="potionmarker">Зельевары</label><br>
    <input class="input-form" type="checkbox" name="category" id="spellmasters" value="SM"><label class="label-form" for="spellmasters">Мастера заклинаний</label><br>

    <input class="button-form" type="submit" value="Применить"/>
</form>
</div>

Adboard/templates/announcement/page_error.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title> Ошибка </title>
</head>
<body>
    <p>Что-то пошло не так ... </p>
    <p>{{error.error}}</p>
    <p>{{error.status}}</p>
</body>
</html>

Adboard/templates/announcement/update_page_form.html
{% extends 'cabinet/profile_article.html' %}

{% block form_update %}
<div class="form-post-update">
    <hr>
    <h3>Редактирование</h3>

    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

    <div class="form-block">
        <div class="block-1"><label for="{{ form.category.id_for_label }}"> {{form.category.label}}: </label></div>
        <div class="block-2">
            {{form.category}}
            <span>{{form.category.errors}}</span>
        </div>
    </div>
    <div class="form-block">
        <div class="block-1"><label for="{{ form.title.id_for_label }}">{{form.title.label}}:</label></div>
        <div class="block-2">
            {{form.title}}
            <span> {{form.title.errors}} </span>
        </div>
    </div>
    <div class="form-block">
        <div class="block-1"><label for="{{ form.article.id_for_label }}">{{form.article.label}}:</label></div>
        <div class="block-2">
            {{form.article}}
            <span> {{form.article.errors}} </span>
        </div>
    </div>
    <div class="form-block">
        <div class="block-1"><label for="{{ form.images.id_for_label }}">{{form.images.label}}:</label></div>
        <div class="block-2">
            {{form.images}}
            <span> {{form.images.errors}} </span>
        </div>
    </div>
    <div class="form-block">
        <div class="block-1"><label for="{{ form.files.id_for_label }}">{{form.files.label}}:</label></div>
        <div class="block-2">
            {{form.files}}
            <span> {{form.files.errors}} </span>
        </div>
    </div>
        <input hidden="hidden" name="mark" value="True">
        <br>
        <input type="submit" value="Сохранить">
    </form>
</div>
{% endblock form_update %}